#!/bin/bash
# Start EC2 instance is stopped

#"${bimalcm:?Need to export bimalcm}"
[ -z "$bimalcm" ] && echo "Need to export bimalcm" && exit 1
[ -z "$AWS_PEM_KEY" ] && echo "Need to set AWS_PEM_KEY to path of PEM file" && exit 1

ssh -i $AWS_PEM_KEY ec2-user@$bimalcm
