#!/bin/bash
# stop EC2 instance if running
[ -z "$AWS_OWNER" ] && echo "Need to export AWS_OWNER" && exit 1

ec2-describe-instances --filter "tag-value=$AWS_OWNER" | grep "^INSTANCE" | awk '{print $2 " " $6}' | grep -i running | awk '{print $1}' | xargs ec2-stop-instances
